### ISSUE TITLE
config.datetime

### ISSUE THREAD

**Issue by lsaenzt** [CalebDepatie/Julianda#8]
I am converting every datetime from Oanda to a Julia DateTime object for easier manipulation of the data.

I think that doing so, makes it unnecesary to provide datetime format in config.  Also, if we include it in the HTTP request we have to deal with the two return types (RFC and Unix). Like this code in coerceCandleStick:

`candle.time = (config.datetime == "RFC3339" ? DateTime(candle.time, RFC) : unix2datetime(candle.time))`

Should we avoid it and stick to RFC? (RFC seems to be the default for Oanda)

**Comment by CalebDepatie** [comment]
Personally I use Unix time for programming, so that's what I've been doing with all my testing but I've intended to make the API able to use both as the config and some of the base parts are modeled after the Oanda python library, but switching to just using DateTime as an input and using one hardcoded format is certainly a cleaner Julia code base, let's go for it.
